PRODUCT_VERSION_MAJOR = 14
PRODUCT_VERSION_MINOR = 0

# Increase CR Version with each major release.
CR_VERSION := 10.4-FAN-EDITION

# Internal version
LINEAGE_VERSION := crDroidAndroid-FE-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-gapps-v$(CR_VERSION)

# Display version
LINEAGE_DISPLAY_VERSION := crDroidAndroid-FE-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-gapps-v$(CR_VERSION)
